repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.90.0
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_tflint

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml


# Security / IaC misconfiguration checks
  - repo: https://github.com/bridgecrewio/checkov
    rev: 3.2.255  # stable version; update periodically
    hooks:
      - id: checkov
        name: checkov (terraform)
        args:
          - --framework
          - terraform
          - --quiet
          - --skip-download
        pass_filenames: false
        stages: [commit, push]
