name: Checkov (Terraform)
on:
  pull_request:
  push:
    branches: [ main, master ]

jobs:
  checkov:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
            directory: ./terraform
            framework: terraform
            quiet: true
            output_format: github_failed_only
            soft_fail: false
